jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Step to check out the code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Step to set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Steps to build and test the application with Maven and run SonarCloud analysis
      - name: Build and test with Maven
        run: |
            mvn -B verify sonar:sonar -Dsonar.projectKey=projettpkatimadevops -Dsonar.organization=tpkatimadevops -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml


